// ESLint for the GUI's JS/TS/Svelte (the Rust side has clippy).
//
// The config lives at the repo root, not in crates/gui/frontend/, because the
// GUI's JS is spread across three directories — the Svelte shell, the shim, and
// the panel types — and only two of them sit under the vite root. A flat config
// resolves its `files` globs relative to itself, so from the root every one of
// them is reachable without `..` escapes.
//
// The type-aware rules read the same tsconfig as `npm run typecheck`, so ESLint
// sees exactly the program tsc does: the shim and the panels included, JS
// checked (`checkJs`).

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import svelteParser from 'svelte-eslint-parser';

const GUI = 'crates/gui';
const TSCONFIG = `${GUI}/frontend/tsconfig.json`;

export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      'target/**',
      // Generated by build.rs when the real bundle has not been built.
      `${GUI}/frontend/dist/**`,
    ],
  },

  // ── The panel JS and the shim: plain JS, typechecked through JSDoc ──────────
  {
    files: [`${GUI}/panel-shim/**/*.js`, `${GUI}/default-config/panel-types/**/*.js`],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.browser,
      parser: tseslint.parser,
      parserOptions: { project: TSCONFIG, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { '@typescript-eslint': tseslint.plugin },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommendedTypeChecked.reduce(
        (all, config) => ({ ...all, ...config.rules }),
        {},
      ),
      // A panel is a pile of `await daemon.call(...)` behind event handlers: an
      // un-awaited promise is a silently swallowed daemon error, which is
      // exactly the bug class this whole pass is about.
      '@typescript-eslint/no-floating-promises': 'error',
      // JSDoc types are advisory to the runtime; a redundant cast is noise, but
      // an *unsafe* one is how a wrong shape reaches the DOM. These fire on the
      // daemon seam (`daemon.call` returns unknown) where the cast is the point,
      // so they are off — `no-explicit-any` still guards the honest escape hatch.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
    },
  },

  // ── The Svelte shell: TypeScript ───────────────────────────────────────────
  {
    files: [`${GUI}/frontend/src/**/*.ts`, `${GUI}/frontend/tests/**/*.ts`],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parser: tseslint.parser,
      parserOptions: { project: TSCONFIG, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { '@typescript-eslint': tseslint.plugin },
    rules: {
      ...js.configs.recommended.rules,
      ...tseslint.configs.recommendedTypeChecked.reduce(
        (all, config) => ({ ...all, ...config.rules }),
        {},
      ),
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
    },
  },

  // ── The Svelte components ──────────────────────────────────────────────────
  ...svelte.configs.recommended.map((config) => ({
    ...config,
    files: [`${GUI}/frontend/src/**/*.svelte`],
  })),
  {
    files: [`${GUI}/frontend/src/**/*.svelte`],
    languageOptions: {
      globals: globals.browser,
      parser: svelteParser,
      parserOptions: { parser: tseslint.parser },
    },
  },

  // The vite/svelte config files are Node, not browser, and are outside the
  // typechecked program — no type-aware rules for them (but they are still TS,
  // so they need the TS parser).
  {
    files: ['*.config.js', `${GUI}/frontend/*.config.ts`],
    languageOptions: { globals: globals.node, parser: tseslint.parser },
    rules: js.configs.recommended.rules,
  },

  // `require-await` cannot tell an accidental `async` from one that is there to
  // satisfy an async interface — which is most of them here: every stub in the
  // tests (`read: async () => []`) and every panel handler that must return a
  // promise. It flagged 95 call sites, all of them correct code.
  {
    rules: { '@typescript-eslint/require-await': 'off' },
  },

  // The tests stub the seams the code talks to (the Tauri `invoke` bridge, the
  // daemon), where the value genuinely is `any` and half the parameters exist
  // only to satisfy a signature.
  {
    files: [`${GUI}/frontend/tests/**/*.ts`],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },

  // PanelHost is the one component whose job *is* to manipulate the DOM the
  // Svelte runtime does not own: it builds a Shadow root per panel and mounts
  // framework-free code into it. Its Map/Set registries are deliberately not
  // reactive — they key live panel instances, and re-rendering on a write to
  // them is exactly what must not happen.
  {
    files: [`${GUI}/frontend/src/lib/panels/PanelHost.svelte`],
    rules: {
      'svelte/no-dom-manipulating': 'off',
      'svelte/prefer-svelte-reactivity': 'off',
    },
  },

  // `latestOnly` forwards a synchronous throw from the wrapped function as a
  // rejection, verbatim — that is the point (it stays call-shaped). Wrapping a
  // non-Error throw into an Error to please the rule would discard what was
  // actually thrown.
  {
    files: [`${GUI}/panel-shim/coalesce.js`],
    rules: { '@typescript-eslint/prefer-promise-reject-errors': 'off' },
  },

  // `no-unnecessary-type-assertion` is wrong about an assertion on an
  // *initializer*: `pageSizes: {} as Record<string, number>` does not restate a
  // type the receiver already has — it is what gives the property that type at
  // all. The rule sees `{}` assignable to `Record<…>`, calls the assertion
  // redundant, and its autofix narrows the declared type to `{}`, which then
  // rejects every write. (Applying that fix broke the store; this is the fix
  // for the fix.)
  {
    files: [`${GUI}/frontend/src/lib/store.svelte.ts`, `${GUI}/frontend/tests/api.test.ts`],
    rules: { '@typescript-eslint/no-unnecessary-type-assertion': 'off' },
  },
];
